### ISSUE TITLE
050-install-openbox-core-v1.sh is missing

### ISSUE THREAD

**Issue by VassilisPallas** [erikdubois/ArchOpenbox#1]
Hi Eric,
I'm trying to install openbox on arch linux. I saw your [tutorial](https://www.youtube.com/watch?v=7_W_rtSb0qY), and you are installing the openbox core with code 50, which is missing from installation folder. Do I have to skip this step and install the "100-install-core-software-v2.sh"?
Thanks.
Vassilis

**Comment by erikdubois** [comment]
script 50 is replaced with others
continue the scripts following the numbers

**Comment by erikdubois** [comment]
Personal folder is ESSENTIAL
